import * as admin from "firebase-admin";
import { onMessagePublished } from "firebase-functions/v2/pubsub";
import { getFluxClient } from "./utils/flux";
import { getGeminiClient } from "./utils/gemini";
import { retryWithBackoff } from "./utils/retry";
import { uploadImageToStorage } from "./utils/storage";

interface ImageGenerationPayload {
  storyId: string;
  userId: string;
  pageIndex: number;
  imagePrompt: string;
  imageProvider: "flux" | "gemini";
  sourceImageUrl?: string; // Only for the first page
  consistencyInput?: {
    // For pages 2-N
    imageUrl: string;
    text: string;
  };
}

export const generateSingleImage = onMessagePublished(
  {
    topic: "generate-story-image",
    secrets: ["FLUX_API_KEY", "GEMINI_API_KEY"],
    timeoutSeconds: 300, // 5 minutes is plenty for one image
    memory: "1GiB",
  },
  async (event) => {
    const payload = event.data.message.json as ImageGenerationPayload;
    // 'illustrationStyle' has been removed from here as it was unused.
    const {
      storyId,
      userId,
      pageIndex,
      sourceImageUrl,
      imagePrompt,
      imageProvider,
      consistencyInput,
    } = payload;
    const isFirstPage = pageIndex === 0;

    console.log(
      `[Worker] Received job for story ${storyId}, page ${pageIndex + 1}`
    );
    const storyRef = admin.firestore().collection("stories").doc(storyId);

    try {
      let finalImageUrl: string;

      if (isFirstPage) {
        // The image is already generated by the orchestrator.
        if (!sourceImageUrl) {
          throw new Error("First page worker received no sourceImageUrl.");
        }
        finalImageUrl = sourceImageUrl;
        console.log(`[Worker] Page 1: Using pre-generated image.`);
      } else {
        // This is a subsequent page, generate a new image now.
        if (!consistencyInput) {
          throw new Error(
            `Page ${pageIndex + 1} worker received no consistencyInput.`
          );
        }

        const subsequentPrompt = `The caption for the input image is "${consistencyInput.text}". In the same style, and with totally consistent characters to the input, generate another image for this caption: "${imagePrompt}"`;

        if (imageProvider === "flux") {
          const fluxClient = getFluxClient();
          finalImageUrl = await retryWithBackoff(() =>
            fluxClient.generateImageWithPolling({
              prompt: subsequentPrompt,
              input_image: consistencyInput.imageUrl,
              aspect_ratio: "1:1",
            })
          );
        } else {
          // Gemini
          const geminiClient = getGeminiClient();
          const base64Data = consistencyInput.imageUrl.split(",")[1];
          if (!base64Data) {
            throw new Error(
              "Could not extract base64 data from consistency input."
            );
          }
          finalImageUrl = await retryWithBackoff(() =>
            geminiClient.editImage(subsequentPrompt, base64Data)
          );
        }
        console.log(`[Worker] Page ${pageIndex + 1}: Generated new image.`);
      }

      // Upload the final image to storage
      const storagePath = await uploadImageToStorage(
        finalImageUrl,
        userId,
        storyId,
        `page-${pageIndex + 1}`
      );
      console.log(`[Worker] Uploaded to ${storagePath}.`);

      // Atomically update the Firestore document
      const updateData: { [key: string]: any } = {
        [`storyContent.${pageIndex}.imageUrl`]: storagePath,
        imagesGenerated: admin.firestore.FieldValue.increment(1),
      };

      if (isFirstPage) {
        // The first page's image is also the cover
        updateData.coverImageUrl = storagePath;
      }

      await storyRef.update(updateData);
      console.log(
        `[Worker] Successfully processed page ${pageIndex + 1} for story ${storyId}.`
      );
    } catch (error) {
      console.error(
        `[Worker] Failed to process page ${pageIndex + 1} for story ${storyId}:`,
        error
      );
      await storyRef.update({
        imageGenerationStatus: "failed",
        imageGenerationError: `Failed on page ${pageIndex + 1}: ${error instanceof Error ? error.message : "Unknown error"}`,
      });
      // Do not re-throw; let other workers continue.
    }
  }
);
